// <auto-generated />
using System;
using APGAnalyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APGAnalyzer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626182311_AddEcwAuditModule")]
    partial class AddEcwAuditModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ApgBaseRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseRateCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BlendRateCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CapitalRateCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CheatFlag")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CureCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("PeerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("PeerGroup");

                    b.HasIndex("Region");

                    b.HasIndex("Source");

                    b.HasIndex("Source", "PeerGroup", "Region", "EffectiveDate")
                        .HasDatabaseName("ix_base_rate_lookup");

                    b.ToTable("apg_base_rates");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ApgResultRecord", b =>
                {
                    b.Property<int>("ClaimIdFk")
                        .HasColumnType("int");

                    b.Property<decimal>("ActualPaid")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("BaseRateApplied")
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CapitalApplied")
                        .HasColumnType("bit");

                    b.Property<decimal>("CompressionPct")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("CorrectApgPayment")
                        .HasColumnType("decimal(14,2)");

                    b.Property<bool>("DiscountingApplied")
                        .HasColumnType("bit");

                    b.Property<string>("LineDetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Overpaid")
                        .HasColumnType("bit");

                    b.Property<string>("PeerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("U6Applied")
                        .HasColumnType("bit");

                    b.Property<bool>("Underpaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("Variance")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("ClaimIdFk");

                    b.ToTable("apg_result");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ApgWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Apg")
                        .HasColumnType("int");

                    b.Property<string>("ApgDescription")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsFinalRate")
                        .HasColumnType("bit");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(12,6)");

                    b.Property<int?>("YearRate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Apg");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("Apg", "EffectiveDate")
                        .IsUnique()
                        .HasDatabaseName("uq_apg_weight_date");

                    b.ToTable("apg_weights");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ClaimAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("ClaimIdFk")
                        .HasColumnType("int");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("LineSeq")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimIdFk");

                    b.ToTable("claim_adjustment");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.CmsRateCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CachedUntil")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ConversionFactor")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("FacilityRate")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("Hcpcs")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Modifier")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal?>("MpRvu")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("NonFacilityRate")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal?>("PeRvu")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalRvu")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("WorkRvu")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CachedUntil");

                    b.HasIndex("Hcpcs", "Modifier", "Locality", "Year")
                        .IsUnique()
                        .HasDatabaseName("uq_cms_rate_cache_key");

                    b.ToTable("cms_rate_cache");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwAuditBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AuditDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PracticeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ecw_audit_batch");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwBillingLag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("ChartLockStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("ClaimDate")
                        .HasColumnType("date");

                    b.Property<string>("ClaimNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DaysApptToLocked")
                        .HasColumnType("int");

                    b.Property<int?>("DaysPnToClaimCreated")
                        .HasColumnType("int");

                    b.Property<string>("EncounterId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PatientAcctNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("ProgressNoteLastLockedOn")
                        .HasColumnType("date");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VisitType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkflowStatus")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("ecw_billing_lag");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwClaimFinancial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppointmentProvider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("BilledCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ClaimDate")
                        .HasColumnType("date");

                    b.Property<string>("ClaimNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClaimStatusCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClaimStatusGroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ClaimVoided")
                        .HasColumnType("bit");

                    b.Property<decimal>("ContractualAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Facility")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FacilityPos")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Patient")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PatientAcctNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PatientAge")
                        .HasColumnType("int");

                    b.Property<string>("PatientGender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("PatientPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PayerCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PayerPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PayerWithheld")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Payments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrimaryPayer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Refund")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RenderingProvider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecondaryPayer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("SelfCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("TertiaryPayer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VisitType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("WriteoffAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ClaimNo");

                    b.ToTable("ecw_claim_financial");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwCptLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("BilledCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BilledUnits")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ClaimDate")
                        .HasColumnType("date");

                    b.Property<string>("ClaimNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ContractualAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CptCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CptDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CptGroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Facility")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FacilityPos")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("FeeScheduleAllowedFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Icd1Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Icd1Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Icd2Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Icd3Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Icd4Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsTelevisit")
                        .HasColumnType("bit");

                    b.Property<string>("Modifier1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Modifier2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Modifier3")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Modifier4")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Patient")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PatientAcctNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PatientPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PayerPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrimaryPayer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RenderingProvider")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WriteoffAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ClaimNo");

                    b.ToTable("ecw_cpt_line");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwPatientAging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ClaimDate")
                        .HasColumnType("date");

                    b.Property<string>("ClaimNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Days0To30")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Days121To150")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Days151To180")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Days31To60")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Days61To90")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Days91To120")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DaysOver180")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NoOfStatementsSent")
                        .HasColumnType("int");

                    b.Property<string>("PatientAcctNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("PatientDob")
                        .HasColumnType("date");

                    b.Property<string>("PatientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("ServiceDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("ecw_patient_aging");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwPayerAging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgingDays")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ClaimDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ClaimFirstSubmittedDate")
                        .HasColumnType("date");

                    b.Property<string>("ClaimNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Days31To60")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Days61To90")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Days91To120")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DaysCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DaysOver120")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("LastSubmissionDate")
                        .HasColumnType("date");

                    b.Property<string>("PatientAcctNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("ServiceDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("IsPrimary");

                    b.ToTable("ecw_payer_aging");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("Charges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ClaimDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ClaimFirstSubmissionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ClaimLastSubmissionDate")
                        .HasColumnType("date");

                    b.Property<string>("ClaimNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PatientAcctNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SubmissionDate")
                        .HasColumnType("date");

                    b.Property<string>("SubmissionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ClaimNo");

                    b.ToTable("ecw_submission");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.FeeScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Hcpcs")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal?>("MaxUnits")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Reimbursement")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("Hcpcs");

                    b.HasIndex("Hcpcs", "EffectiveDate")
                        .HasDatabaseName("ix_fee_schedule_lookup");

                    b.ToTable("fee_schedule");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.HcpcsToEapg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Eapg")
                        .HasColumnType("int");

                    b.Property<string>("EapgCategory")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EapgDesc")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EapgServiceLine")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EapgType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Hcpcs")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateOnly?>("MidQuarterEffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MidQuarterEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("QuarterEffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("QuarterEndDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Eapg");

                    b.HasIndex("EapgType");

                    b.HasIndex("Hcpcs");

                    b.HasIndex("QuarterEffectiveDate");

                    b.HasIndex("Hcpcs", "QuarterEffectiveDate")
                        .HasDatabaseName("ix_hcpcs_eapg_code_date");

                    b.ToTable("hcpcs_to_eapg");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.Icd10ToEapg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DxCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("Eapg")
                        .HasColumnType("int");

                    b.Property<string>("EapgCategory")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EapgDesc")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EapgServiceLine")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EapgType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("DxCode");

                    b.HasIndex("Eapg");

                    b.HasIndex("EapgType");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("DxCode", "EffectiveDate")
                        .HasDatabaseName("ix_icd10_eapg_code_date");

                    b.ToTable("icd10_to_eapg");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ParsedClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllowedAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("BilledAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("ClaimFilingIndicator")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("ClaimId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClaimStatus")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfService")
                        .HasColumnType("date");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("LinkedClaimIdFk")
                        .HasColumnType("int");

                    b.Property<string>("OtherDiagnosesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("PatientId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("PatientResponsibility")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("PayerId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PayerName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PrincipalDiagnosis")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderNpi")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("DateOfService");

                    b.HasIndex("FileId");

                    b.HasIndex("FileType");

                    b.HasIndex("LinkedClaimIdFk");

                    b.HasIndex("ProviderNpi");

                    b.HasIndex("OwnerUserId", "CreatedAt")
                        .HasDatabaseName("ix_parsed_claim_owner_created");

                    b.ToTable("parsed_claim");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ParsedServiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllowedAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("BilledAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("ClaimIdFk")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateOfService")
                        .HasColumnType("date");

                    b.Property<int>("LineSeq")
                        .HasColumnType("int");

                    b.Property<string>("ModifiersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("RevenueCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaimIdFk");

                    b.HasIndex("ProcedureCode");

                    b.ToTable("parsed_service_line");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ProviderConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CapitalAddonEligible")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CapitalAddonRate")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("CmsLocality")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("CountyCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Npi")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeerGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RateCodeOverride")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Region")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OwnerUserId", "IsActive")
                        .HasDatabaseName("ix_provider_config_owner_active");

                    b.ToTable("provider_config");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ProviderCounty", b =>
                {
                    b.Property<int>("CountyCode")
                        .HasColumnType("int");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HealthHomePhase")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("CountyCode");

                    b.HasIndex("CountyName")
                        .IsUnique();

                    b.ToTable("provider_county");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.PxBasedWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Hcpcs")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal?>("UnitsLimit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(12,6)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("Hcpcs");

                    b.HasIndex("Hcpcs", "EffectiveDate")
                        .HasDatabaseName("ix_px_weight_lookup");

                    b.ToTable("px_based_weights");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ApgResultRecord", b =>
                {
                    b.HasOne("APGAnalyzer.Models.Domain.ParsedClaim", "Claim")
                        .WithOne("ApgResult")
                        .HasForeignKey("APGAnalyzer.Models.Domain.ApgResultRecord", "ClaimIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ClaimAdjustment", b =>
                {
                    b.HasOne("APGAnalyzer.Models.Domain.ParsedClaim", "Claim")
                        .WithMany("Adjustments")
                        .HasForeignKey("ClaimIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwBillingLag", b =>
                {
                    b.HasOne("APGAnalyzer.Models.Domain.EcwAuditBatch", "Batch")
                        .WithMany("BillingLags")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwClaimFinancial", b =>
                {
                    b.HasOne("APGAnalyzer.Models.Domain.EcwAuditBatch", "Batch")
                        .WithMany("ClaimFinancials")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwCptLine", b =>
                {
                    b.HasOne("APGAnalyzer.Models.Domain.EcwAuditBatch", "Batch")
                        .WithMany("CptLines")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwPatientAging", b =>
                {
                    b.HasOne("APGAnalyzer.Models.Domain.EcwAuditBatch", "Batch")
                        .WithMany("PatientAgings")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwPayerAging", b =>
                {
                    b.HasOne("APGAnalyzer.Models.Domain.EcwAuditBatch", "Batch")
                        .WithMany("PayerAgings")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwSubmission", b =>
                {
                    b.HasOne("APGAnalyzer.Models.Domain.EcwAuditBatch", "Batch")
                        .WithMany("Submissions")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ParsedClaim", b =>
                {
                    b.HasOne("APGAnalyzer.Models.Domain.ParsedClaim", "LinkedClaim")
                        .WithMany()
                        .HasForeignKey("LinkedClaimIdFk")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LinkedClaim");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ParsedServiceLine", b =>
                {
                    b.HasOne("APGAnalyzer.Models.Domain.ParsedClaim", "Claim")
                        .WithMany("ServiceLines")
                        .HasForeignKey("ClaimIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.EcwAuditBatch", b =>
                {
                    b.Navigation("BillingLags");

                    b.Navigation("ClaimFinancials");

                    b.Navigation("CptLines");

                    b.Navigation("PatientAgings");

                    b.Navigation("PayerAgings");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("APGAnalyzer.Models.Domain.ParsedClaim", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("ApgResult");

                    b.Navigation("ServiceLines");
                });
#pragma warning restore 612, 618
        }
    }
}
